site_name: gmpfeifer Wiki
site_description: gmpfeifer's MKDocs Test
site_url: https://gmpfeifer.github.io/gmpfeifer-mkdocs-publisher/
copyright: Copyright &copy; 2022 Georg Michael Pfeifer

theme:
  name: "material"
  logo: assets/logo/gm.png
  favicon: assets/logo/gm.png
  custom_dir: overrides
  font:
    text: Karla
    code: Ubuntu Mono
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.indexes
    # - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - toc.follow
    - content.tooltips
    - content.code.annotate

# Extensions
markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: gmpfeifer
      repo: gmpfeifer-mkdocs-publisher
  - pymdownx.betterem:
      smart_enable: all
  - md_in_html
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  #- mdx_breakless_lists <----- This line breaks mkdocs CodeBlocks (adds empty line to yml code Examples)
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: dataview
          class: dataview
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search:
      lang:
        - de
        - en
  - ezlinks:
      wikilinks: true
  - mermaid2
  - awesome-pages
  - tooltipster-links
  - embed_file
  - roamlinks
extra_javascript:
  - assets/js/mathjax.js
  - assets/js/utils.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/tooltipster.bundle.js
extra_css:
  - assets/css/img-grids-floats.css
  - assets/css/utils.css
  - assets/css/custom_attributes.css
  - assets/css/tooltipster.bundle.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
extra:
  generator: true
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gmpfeifer
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_georgmichael_
    - icon: fontawesome/brands/github
      link: https://github.com/gmpfeifer
    - icon: fontawesome/brands/xing
      link: https://www.xing.com/profile/GeorgMichael_Pfeifer/cv
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/georg-michael-pfeifer-4355031b7/

nav:
  - Willkommen: index.md
  - Obsidian Notizen:
      - Obsidian Notizen/index.md
      - FH:
          - MobCo:
              - Großes Projekt:
                  - Hardware Beschaffung: Obsidian Notizen/FH/MobCo/Großes Projekt/Großes Projekt - Hardwarebeschaffung.md
                  - Flashen des eMMC Moduls: Obsidian Notizen/FH/MobCo/Großes Projekt/Großes Projekt - eMMC flashen.md
                  - Einrichtung der Software: Obsidian Notizen/FH/MobCo/Großes Projekt/Großes Projekt - Installation OMV.md
              - Ideen & Experimente:
                  - 11ty Installation: Obsidian Notizen/FH/MobCo/Ideen & Experimente/11ty Grundinstallation.md
                  - Github Actions Runner: Obsidian Notizen/FH/MobCo/Ideen & Experimente/Github Actions Runner.md
                  - Welches 11ty Starter Template: Obsidian Notizen/FH/MobCo/Ideen & Experimente/Welches Starter Template?.md
      - Musiktheorie: Obsidian Notizen/Music Theory.md
      - Testnotiz: Obsidian Notizen/Testnotiz von gmpfeifer.md
